package Frame;

import javax.swing.DefaultListModel;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import java.util.logging.*;
//import javax.swing.ImageIcon;
//import javax.swing.JOptionPane;

/**
 *
 * @author Laden
 */
public class MainFrame extends javax.swing.JFrame {

    private final DefaultListModel modelSpringBed;
    private final ArrayList<String> dataIdSpringBed = new ArrayList();
    private final ArrayList<BobotPenilaian> dataSpringBed = new ArrayList();
    private PreparedStatement pst;
    private ResultSet result;
    private Statement stm;
    private final Koneksi koneksi = new Koneksi();
    
    public MainFrame() {
        initComponents();
        modelSpringBed = new DefaultListModel();
        pnlBedList.setModel(modelSpringBed);
        getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnExit = new Frame.CButton();
        cButton7 = new Frame.CButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlBedList = new javax.swing.JList<>();
        btnUpdate = new Frame.CButton();
        btnDelete = new Frame.CButton();
        btnResult = new Frame.CButton();
        jTextFieldHarga = new javax.swing.JTextField();
        jTextFieldBahan = new javax.swing.JTextField();
        jTextFieldKeempukan = new javax.swing.JTextField();
        jTextFieldWarna = new javax.swing.JTextField();
        jTextFieldLebar = new javax.swing.JTextField();
        jTextFieldFiturTambahan = new javax.swing.JTextField();
        jLabelHarga = new javax.swing.JLabel();
        jLabelBahan = new javax.swing.JLabel();
        jLabelKeempukan = new javax.swing.JLabel();
        jLabelWarna = new javax.swing.JLabel();
        jLabelLebar = new javax.swing.JLabel();
        jLabelFiturTambah = new javax.swing.JLabel();
        btnInsert = new Frame.CButton();
        jLabelGaransi = new javax.swing.JLabel();
        jTextFieldGaransi = new javax.swing.JTextField();
        jLabelMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        btnExit.setText("cButton6");

        cButton7.setText("cButton7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(389, 389, 389))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        pnlBedList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List Spring Bed", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Yu Gothic Medium", 1, 14))); // NOI18N
        pnlBedList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBedListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pnlBedList);

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnResult.setText("RESULT");
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });

        jTextFieldHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHargaActionPerformed(evt);
            }
        });

        jTextFieldBahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBahanActionPerformed(evt);
            }
        });

        jTextFieldKeempukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKeempukanActionPerformed(evt);
            }
        });

        jTextFieldWarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWarnaActionPerformed(evt);
            }
        });

        jTextFieldLebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLebarActionPerformed(evt);
            }
        });

        jTextFieldFiturTambahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFiturTambahanActionPerformed(evt);
            }
        });

        jLabelHarga.setText("HARGA");

        jLabelBahan.setText("BAHAN");

        jLabelKeempukan.setText("KEEMPUKAN");

        jLabelWarna.setText("WARNA");

        jLabelLebar.setText("LEBAR");

        jLabelFiturTambah.setText("FITUR TAMBAHAN");

        btnInsert.setText("INSERT");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        jLabelGaransi.setText("MEMILIKI GARANSI");

        jLabelMenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu.setText("MENU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 355, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGaransi)
                            .addComponent(jTextFieldGaransi, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(btnInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelFiturTambah)
                                .addComponent(jLabelBahan)
                                .addComponent(jLabelKeempukan)
                                .addComponent(jLabelWarna)
                                .addComponent(jLabelLebar)
                                .addComponent(jLabelHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jTextFieldBahan, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                        .addComponent(jTextFieldHarga, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldWarna)
                        .addComponent(jTextFieldKeempukan, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldFiturTambahan)
                        .addComponent(jTextFieldLebar, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(jLabelGaransi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldGaransi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jLabelHarga)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabelBahan)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextFieldBahan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabelKeempukan)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextFieldKeempukan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabelWarna)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextFieldWarna, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabelLebar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextFieldLebar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabelFiturTambah)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextFieldFiturTambahan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(61, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldKeempukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKeempukanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKeempukanActionPerformed

    private void jTextFieldWarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWarnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWarnaActionPerformed

    private void jTextFieldHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHargaActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        InputFrame inputFrame = new InputFrame();
        inputFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void jTextFieldBahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBahanActionPerformed

    private void jTextFieldLebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLebarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLebarActionPerformed

    private void jTextFieldFiturTambahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFiturTambahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFiturTambahanActionPerformed

    private void pnlBedListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBedListMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){ // event klik 2x untuk masuk ke TaskFrame
//            setLokasi();
//            TaskFrame task = new TaskFrame(dataIdKategori.get(pnlKategori.getSelectedIndex()));
//            task.setVisible(true);
//            this.dispose();
        }
        if(!pnlBedList.isSelectionEmpty() && evt.getButton() == 1){ // untuk menampilkan tanggal dan deskripsi
            try {
                int index = pnlBedList.getSelectedIndex();
                String sql = "SELECT * FROM dataSpringBed WHERE id=?";
                Connection cn = koneksi.getKoneksi();
                pst = cn.prepareStatement(sql);
                pst.setString(1, dataIdSpringBed.get(index));
                result = pst.executeQuery();
                String harga = "0",bahan = "0",keempukan = "0",warna = "0",lebar = "0",fitur = "0",garansi = "0",nilaiV = "0";
                jTextFieldHarga.setText("");
                jTextFieldBahan.setText("");
                jTextFieldKeempukan.setText("");
                jTextFieldWarna.setText("");
                jTextFieldLebar.setText("");
                jTextFieldFiturTambahan.setText("");
                jTextFieldGaransi.setText("");
                while(result.next()){
                    harga = result.getString(3);
                    bahan = result.getString(4);
                    keempukan = result.getString(5);
                    warna = result.getString(6);
                    lebar = result.getString(7);
                    fitur = result.getString(8);
                    garansi = result.getString(9);
                    
                }
                jTextFieldHarga.setText(harga);
                jTextFieldKeempukan.setText(keempukan);
                jTextFieldBahan.setText(bahan);
                jTextFieldWarna.setText(warna);
                jTextFieldLebar.setText(lebar);
                jTextFieldFiturTambahan.setText(fitur);
                if(garansi.equals("0")){
                    jTextFieldGaransi.setText("Tidak ada"); 
                } else {
                    jTextFieldGaransi.setText("Ada"); 
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(pnlBedList, ex);
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    result.close();
                    pst.close();
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } 
        }
    }//GEN-LAST:event_pnlBedListMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if(pnlBedList.isSelectionEmpty()){
            JOptionPane.showMessageDialog(pnlBedList, "Pilih data dulu");
        } else {
            InputFrame input = new InputFrame(true,dataIdSpringBed.get(pnlBedList.getSelectedIndex()));
            input.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(pnlBedList.isSelectionEmpty()){ // message jika tidak ada kategori yang di select
            JOptionPane.showMessageDialog(pnlBedList, "Pilih data dulu");
        } else {
            try {
                // menghapus item kategori
                String index = dataIdSpringBed.get(pnlBedList.getSelectedIndex());
                String sql = "DELETE FROM dataSpringBed WHERE id=?";
                Connection cn = koneksi.getKoneksi();
                pst = cn.prepareStatement(sql);
                pst.setString(1, index);
                pst.execute();
                // menghapus item kegiatan
                sql = "DELETE FROM dataSpringBed WHERE id=?";
                PreparedStatement pst1 = cn.prepareStatement(sql);
                pst1.setString(1, index);
                pst1.execute();
                dataIdSpringBed.remove(index);
                getData();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(pnlBedList, "Gagal menghapus data : "+ex);
            } finally {
                try {
                    pst.close();
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } 
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
        // TODO add your handling code here:
        MetodeWP wp = new MetodeWP(dataSpringBed);
    }//GEN-LAST:event_btnResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Frame.CButton btnDelete;
    private Frame.CButton btnExit;
    private Frame.CButton btnInsert;
    private Frame.CButton btnResult;
    private Frame.CButton btnUpdate;
    private Frame.CButton cButton7;
    private javax.swing.JLabel jLabelBahan;
    private javax.swing.JLabel jLabelFiturTambah;
    private javax.swing.JLabel jLabelGaransi;
    private javax.swing.JLabel jLabelHarga;
    private javax.swing.JLabel jLabelKeempukan;
    private javax.swing.JLabel jLabelLebar;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelWarna;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldBahan;
    private javax.swing.JTextField jTextFieldFiturTambahan;
    private javax.swing.JTextField jTextFieldGaransi;
    private javax.swing.JTextField jTextFieldHarga;
    private javax.swing.JTextField jTextFieldKeempukan;
    private javax.swing.JTextField jTextFieldLebar;
    private javax.swing.JTextField jTextFieldWarna;
    private javax.swing.JList<String> pnlBedList;
    // End of variables declaration//GEN-END:variables
    private void getData(){
        try{
            modelSpringBed.removeAllElements();
            dataSpringBed.clear();
            Connection cn = koneksi.getKoneksi();
            stm = cn.createStatement();
            result = stm.executeQuery("SELECT * FROM dataSpringBed");
            while(result.next()){
                modelSpringBed.addElement(result.getString(2));
                dataIdSpringBed.add(result.getString(1));
                dataSpringBed.add(new BobotPenilaian(result.getString(2),result.getInt(3),result.getInt(4),result.getInt(5),result.getInt(6),result.getInt(7), result.getInt(8), result.getInt(9)));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(pnlBedList, "Error : "+ ex);
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                result.close();
                stm.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(pnlBedList, "Error set data : "+ ex);
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }
}
